[package]
name = "wyvern"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
image = "0.25.1"
rand = "0.8.5"
clap = { version = "4.5.11", features = ["derive"] }
num_cpus = "1.16.0"
